shell = { program = "wsl", args = ["-d", "Debian"]}
# working_directory = "/home/michaelz"


[window]
title = "Alacritty - Dev"
dynamic_title = false
padding = {x = 10, y = 10}
decorations = "full"
startup_mode = "Maximized"
opacity = 0.9
blur = true

[font]

normal = { family = "FiraCode Nerd Font Mono",style = "Regular"}
bold = { family = "FiraCode Nerd Font Mono",style = "Bold"}
italic = { family = "FiraCode Nerd Font Mono",style = "Italic"}
bold_italic = { family = "FiraCode Nerd Font Mono",style = "Bold Italic"}

size = 12.0
